name: Booking Bot

on:
  schedule:
    - cron: '59 22 * * *'
  workflow_dispatch:

jobs:
  booking:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install selenium webdriver-manager

      - name: Run booking script 1
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          URL_LOGIN: ${{ secrets.URL_LOGIN }}
          URL_PRENOTAZIONE: ${{ secrets.URL_PRENOTAZIONE }}
          USERNAMEM: ${{ secrets.USERNAMEM }}
          PASSWORDM: ${{ secrets.PASSWORDM }}
        run: python script.py

      - name: Run booking script 2
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          URL_LOGIN: ${{ secrets.URL_LOGIN }}
          URL_PRENOTAZIONE: ${{ secrets.URL_PRENOTAZIONE }}
          USERNAMEM: ${{ secrets.USERNAMEM }}
          PASSWORDM: ${{ secrets.PASSWORDM }}
        run: python script2.py
